USE [RP_BI_RESUMENES]
GO

/****** Object:  Table [dbo].[DIM_EVENTOS]    Script Date: 14/02/2026 23:56:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_EVENTOS](
	[IDEVENTO] [int] IDENTITY(1,1) NOT NULL,
	[EVENTO] [nvarchar](200) NULL,
	[ESFERIADO] [nvarchar](1) NULL,
	[USARENPRESUPUESTO] [nvarchar](1) NULL,
	[ESINTERNO] [nvarchar](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDEVENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [RP_BI_RESUMENES]
GO

/****** Object:  Table [dbo].[DIM_EVENTOS_FECHAS]    Script Date: 14/02/2026 23:57:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_EVENTOS_FECHAS](
	[IDEVENTO] [int] NULL,
	[FECHA] [date] NULL,
	[FECHA_EFECTIVA] [date] NULL,
	[Canal] [nchar](100) NULL,
	[GrupoAlmacen] [int] NULL
) ON [PRIMARY]
GO


