-- Query to check current column names in RSM_ALCANCE_DIARIO
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'RSM_ALCANCE_DIARIO' 
ORDER BY ORDINAL_POSITION;

-- Sample data to see values
SELECT TOP 5 * 
FROM RSM_ALCANCE_DIARIO 
WHERE Fecha >= '2026-01-01'
ORDER BY Fecha;
