-- Test query to check GRUPOSALMACENCAB table structure and data
SELECT TOP 5 * FROM GRUPOSALMACENCAB WHERE CODVISIBLE = 20;

-- Check column names
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'GRUPOSALMACENCAB';
