-- Agregar columnas de formato de reporte a APP_USUARIOS
IF COL_LENGTH('APP_USUARIOS', 'PctDisplayMode') IS NULL
BEGIN
    ALTER TABLE APP_USUARIOS ADD PctDisplayMode VARCHAR(20) DEFAULT 'base100';
END
GO

IF COL_LENGTH('APP_USUARIOS', 'PctDecimals') IS NULL
BEGIN
    ALTER TABLE APP_USUARIOS ADD PctDecimals INT DEFAULT 1;
END
GO

IF COL_LENGTH('APP_USUARIOS', 'ValueDisplayMode') IS NULL
BEGIN
    ALTER TABLE APP_USUARIOS ADD ValueDisplayMode VARCHAR(20) DEFAULT 'completo';
END
GO

IF COL_LENGTH('APP_USUARIOS', 'ValueDecimals') IS NULL
BEGIN
    ALTER TABLE APP_USUARIOS ADD ValueDecimals INT DEFAULT 0;
END
GO
